@startuml
scale 1.5


class Application {
    + evidSrv : char
    + idCredit : number
    + agregatorResult : AgregatorResult
}


Application*--workflow
Application*--timeZone
Application*--systemMessage
Application*--sysdate
Application*--stopList
Application*--sourceData
Application*--smData
Application*--scoResult
Application*--scanResult
Application*--salesPoint
Application*--rescoResult
Application*--registerPreResult
Application*--randomNumber8
Application*--randomNumber7
Application*--randomNumber6
Application*--randomNumber5
Application*--randomNumber4
Application*--randomNumber3
Application*--randomNumber2
Application*--randomNumber1
Application*--processType
Application*--preResult
Application*--prelimResult
Application*--prelimPreResult
Application*--prelimCbResult
Application*--preApprResult
Application*--postResult
Application*--phoneVerification
Application*--persons
Application*--personContact
Application*--partnerName
Application*--outputData
Application*--offlineRevFinalResult
Application*--offlineResult
Application*--offlineData
Application*--offlineCashFinalResult
Application*--lastOfflineScoreXsellSC
Application*--lastOfflineScoreXsellRD
Application*--isOuterLimit
Application*--idRequest
Application*--idPerson
Application*--idCredit
Application*--fpsResult
Application*--featureControl
Application*--evidSrv
Application*--employeeAdminType
Application*--empCode
Application*--documents
Application*--credit
Application*--consent
Application*--channelSale
Application*--cbResult
Application*--calculateOnlineLimit
Application*--calculateLinkedRDLimits
Application*--bombInBank
Application*--bdResult
Application*--appVerifIncome
Application*--application
Application*--applicantData
Application*--appIncomeCache
Application*--appIncome
Application*--agregatorResult
workflow*--stageCounters
updatedData*--persons
trial*--wfDetails
trial*--scoringDetails
trial*--rgDetails
trial*--limitDetails
trial*--hcDetails
sourceData*--verificationResults
sourceData*--verificationDetailResults
sourceData*--updatedData
sourceData*--undesirablePerson
sourceData*--onlineLimit
sourceData*--nextWorkflows
sourceData*--linkedVerificationResults
sourceData*--linkedVerificationDetailResults
sourceData*--hardCheckPredictors
sourceData*--extData
sourceData*--crossClientChecks
sourceData*--creditLimit
sourceData*--biometricData
sourceData*--behaviourData
smuid_data*--pfr_account_advice
smuid_data*--my_credit_ob_bank_applications
smuid_data*--my_credit_ob_back_web_cnt_180
smuid_data*--my_credit_ob_back_mobile_cnt_180
smData*--smuid_data
smData*--online_behav_os_web
smData*--online_behav_os_mobile
smData*--online_behav_min_dist
smData*--online_behav_device_type_s_cnt
smData*--online_behav_device_type
smData*--online_behav_device_s_cnt
smData*--online_behav_device
smData*--geo_activity
smData*--client_score
score*--persons
scanResult*--trial
scanResult*--persons
scanResult*--client
salesPoint*--products
rescoResult*--trial
previousApplicationsFraud*--persons
previousApplications*--rejectData
previousApplications*--persons
previousApplications*--personContact
previousApplications*--approvalData
previousApplications*--appArray
persons*--employmentAddress
persons*--employment
persons*--contactAddress
person*--employment
outputData*--uwInfo
outputData*--savedInfo
outputData*--resultTrace
outputData*--offers
outputData*--checkPersons
online_behav_os_web*--my_credit_ob_os_web_180
online_behav_os_mobile*--my_credit_ob_os_mobile_180
online_behav_min_dist*--my_credit_ob_min_distance_reg_addr
online_behav_min_dist*--my_credit_ob_min_distance_emp_addr
online_behav_min_dist*--my_credit_ob_min_distance_cont_addr
online_behav_device_type_s_cnt*--my_credit_ob_dtype_sc_30
online_behav_device_type*--my_credit_ob_device_type_180
online_behav_device_s_cnt*--my_credit_ob_device_sess_cnt_30
online_behav_device*--my_credit_ob_device_180
onlineLimit*--persons
offlineResult*--score
limitDetails*--pseudo
limitDetails*--fact
limit*--persons
hardCheckPredictors*--persons
geo_activity*--mts_geo_activity
expense*--persons
derivedData*--persons
crossClientChecks*--sameMobileCheck
crossClientChecks*--sameIdentCard
creditLimit*--persons
creditBureau*--scoring
creditBureau*--persons
creditBureau*--creditData
creditBureau*--bureauResponse
credit*--supplement
credit*--service
credit*--persons
credit*--onlineApp
credit*--insurance
credit*--goods
credit*--fps
credit*--creditProduct
credit*--creditPreferences
credit*--creditBureau
credit*--consolidatedData
credit*--afs
client_score*--yandex_score
client_score*--tele2_score
client_score*--mts_score_features
client_score*--mts_score
client_score*--mailru_sp_score
client_score*--mailru_score
client_score*--juicyscore_score
clientReality*--persons
biometricData*--persons
behaviourData*--persons
applicantData*--previousApplicationsFraud
applicantData*--previousApplications
applicantData*--expense
applicantData*--creditLimit
applicantData*--clientReality
applicantData*--cars
applicantData*--campaigns
appChars*--tw
appChars*--pfr
appChars*--incomes
appChars*--bki
appArray*--salesPoint
appArray*--person
appArray*--credit

@enduml